version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 'python'
    working_dir: /usr/src/app
    volumes:
      - './:/usr/src/app'
    ports:
      - '3300:3300'
    command: python ./src/index.py
